version: '3.3'

networks:
  internal:
    external: false

services:
  gc2core:
    image: gc2core:dev
    privileged: true
    networks:
      - internal
      - default
    ports:
      - "8080:80"
    environment:
      - POSTGIS_HOST=postgis
      - POSTGIS_DB=postgres
      - POSTGIS_USER=gc2
      - POSTGIS_PORT=5432
      - POSTGIS_PW=1234
      - POSTGIS_PGBOUNCER=false
  redis:
    image: redis
    networks:
      - internal
  postgis:
    image: mapcentia/postgis
    networks:
      - internal
    environment:
      - GC2_USER=gc2
      - GC2_PASSWORD=1234
      - GC2_LOCALE=da_DK.UTF-8
  vidi:
    image: mapcentia/vidi
    networks:
      - internal
      - default
    ports:
      - "3000:3000"
    environment:
      - GC2_HOST=http://gc2core
