#!/usr/bin/php
<?php
ini_set("display_errors", "on");
error_reporting(E_ERROR | E_WARNING | E_PARSE);

use \app\conf\Connection;
use \app\conf\App;
use \app\models\Database;

header("Content-type: text/plain");
include_once('/var/www/geocloud2/app/vendor/autoload.php');
include_once("/var/www/geocloud2/app/conf/App.php");

new \app\conf\App();
\app\inc\Cache::setInstance();

if (isset($argv[1])) {
    $_SERVER['HTTP_HOST'] = $argv[1];

} else {
    echo "Host is not set. Use ./build_files [host.com]\n";
    exit(1);
}

if (isset($argv[2])) {
    $db = $argv[2];

} else {
    echo "Database is not set. Use ./build_files [host.com] [database]\n";
    exit(1);
}

App::$param['host'] = $_SERVER['HTTP_HOST'];

Connection::$param['postgisdb'] = $db;

$database = new Database();
$schemas = $database->listAllSchemas();

$response = [];
$mapfile = new \app\controllers\Mapfile();
if (!empty($schemas["data"])) foreach ($schemas["data"] as $schema) {
    Connection::$param['postgisschema'] = $schema["schema"];
    $res = $mapfile->get_index();
    $response["data"][] = [$res[0]["ch"], $res[1]["ch"]];
}
$response["success"] = true;
print_r($response);