#!/usr/bin/php
<?php

header("Content-type: text/plain");

$dir = "/var/www/geocloud2/app";

if ($dir . "/files") {
    die("Seems that bitmaps are moved. Doing nothing.\n");
}

if ($handle = opendir($dir . "/tmp")) {
    while (false !== ($entry = readdir($handle))) {
        if ($entry !== "." && $entry !== "..") {
            $bitmapDir = $dir . "/tmp/" . $entry . "/__bitmaps";

            if (file_exists($bitmapDir)) {
                mkdir($dir . "/files/{$entry}");
                rename($bitmapDir, $dir . "/files/{$entry}/__bitmaps");
            }

        }
    }
    closedir($handle);
}






