#!/usr/bin/php
<?php

header("Content-type: text/plain");

$dir = "/var/www/geocloud2/app";

if (file_exists($dir . "/files")) {
    die("Seems that bitmaps are moved. Doing nothing.\n");
}

if ($handle = opendir($dir . "/tmp")) {
    while (false !== ($entry = readdir($handle))) {
        if ($entry !== "." && $entry !== "..") {
            $bitmapDir = $dir . "/tmp/" . $entry . "/__bitmaps";

            if (file_exists($bitmapDir)) {
                mkdir($dir . "/files");
                mkdir($dir . "/files/{$entry}");
                rcopy($bitmapDir, $dir . "/files/{$entry}/__bitmaps");
            }

        }
    }
    closedir($handle);
}

// Function to Copy folders and files
function rcopy($src, $dst) {
    if (is_dir ( $src )) {
        mkdir ( $dst );
        $files = scandir ( $src );
        foreach ( $files as $file )
            if ($file != "." && $file != "..")
                rcopy ( "$src/$file", "$dst/$file" );
    } else if (file_exists ( $src ))
        copy ( $src, $dst );
}







