#!/usr/bin/php
<?php
use \app\conf\App;
use \app\models\Database;
use \app\models\Layer;
use \app\inc\Util;
use \app\inc\Model;

header("Content-type: text/plain");
include_once("../App.php");
new \app\conf\App();
Database::setDb("flis");
$conn = new Model();
$layer = new Layer();
$sql = "SELECT * FROM settings.geometry_columns_join";
$result = $conn->execQuery($sql);
echo $conn->PDOerror[0];
$count = 0;
$gc2host = isset(App::$param["ckan"]["gc2host"]) ? App::$param["ckan"]["gc2host"] : App::$param["host"];

while ($row = $conn->fetchRow($result)) {

    if (isset($row["meta"])) {
        $meta = json_decode($row["meta"]);

        if (isset($meta->ckan_update) && $meta->ckan_update) {
            //print_r($meta);

            $url = "http://127.0.0.1/api/v1/ckan/" . Database::getDb() . "?id=" . $row["_key_"] . "&host=" . $gc2host;
            try {
                print Util::wget($url);
            } catch (Exception $exception) {
                print $exception->getMessage();
            }
        } else {
            $uuid = $layer->getUuid($row["_key_"]);
            print_r($layer::deleteCkan($uuid["uuid"]));
        }
    } else {
        $uuid = $layer->getUuid($row["_key_"]);
        print_r($layer::deleteCkan($uuid["uuid"]));
    }
}