export const GET_GC2_CONFIGURATION_REQUEST = 'App/GET_GC2_CONFIGURATION_REQUEST';
export const GET_GC2_CONFIGURATION_SUCCESS = 'App/GET_GC2_CONFIGURATION_SUCCESS';

export const CHECK_AUTHORIZATION_REQUEST = 'App/CHECK_AUTHORIZATION_REQUEST';
export const CHECK_AUTHORIZATION_SUCCESS = 'App/CHECK_AUTHORIZATION_SUCCESS';
export const CHECK_AUTHORIZATION_FAILURE = 'App/CHECK_AUTHORIZATION_FAILURE';

export const SIGN_IN_REQUEST = 'App/SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'App/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'App/SIGN_IN_FAILURE';

export const GET_DATABASES_RESET = 'App/GET_DATABASES_RESET';
export const GET_DATABASES_REQUEST = 'App/GET_DATABASES_REQUEST';
export const GET_DATABASES_SUCCESS = 'App/GET_DATABASES_SUCCESS';
export const GET_DATABASES_FAILURE = 'App/GET_DATABASES_FAILURE';

export const CREATE_USER_RESET = 'App/CREATE_USER_RESET';
export const CREATE_USER_REQUEST = 'App/CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'App/CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'App/CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'App/UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'App/UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'App/UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'App/DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'App/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'App/DELETE_USER_FAILURE';

export const UPDATE_USER_PASSWORD_SUCCESS = 'App/UPDATE_USER_PASSWORD_SUCCESS';

export const GET_SUBUSERS_REQUEST = 'App/GET_SUBUSERS_REQUEST';
export const GET_SUBUSERS_SUCCESS = 'App/GET_SUBUSERS_SUCCESS';
export const GET_SUBUSERS_FAILURE = 'App/GET_SUBUSERS_FAILURE';

export const GET_SCHEMAS_REQUEST = 'App/GET_SCHEMAS_REQUEST';
export const GET_SCHEMAS_SUCCESS = 'App/GET_SCHEMAS_SUCCESS';
export const GET_SCHEMAS_FAILURE = 'App/GET_SCHEMAS_FAILURE';

export const GET_CONFIGURATIONS_REQUEST = 'App/GET_CONFIGURATIONS_REQUEST';
export const GET_CONFIGURATIONS_SUCCESS = 'App/GET_CONFIGURATIONS_SUCCESS';
export const GET_CONFIGURATIONS_FAILURE = 'App/GET_CONFIGURATIONS_FAILURE';

export const GET_CONFIGURATION_REQUEST = 'App/GET_CONFIGURATION_REQUEST';
export const GET_CONFIGURATION_SUCCESS = 'App/GET_CONFIGURATION_SUCCESS';
export const GET_CONFIGURATION_FAILURE = 'App/GET_CONFIGURATION_FAILURE';

export const CREATE_UPDATE_CONFIGURATION_RESET = 'App/CREATE_UPDATE_CONFIGURATION_RESET';

export const CREATE_CONFIGURATION_REQUEST = 'App/CREATE_CONFIGURATION_REQUEST';
export const CREATE_CONFIGURATION_SUCCESS = 'App/CREATE_CONFIGURATION_SUCCESS';
export const CREATE_CONFIGURATION_FAILURE = 'App/CREATE_CONFIGURATION_FAILURE';

export const UPDATE_CONFIGURATION_REQUEST = 'App/UPDATE_CONFIGURATION_REQUEST';
export const UPDATE_CONFIGURATION_SUCCESS = 'App/UPDATE_CONFIGURATION_SUCCESS';
export const UPDATE_CONFIGURATION_FAILURE = 'App/UPDATE_CONFIGURATION_FAILURE';

export const DELETE_CONFIGURATION_REQUEST = 'App/DELETE_CONFIGURATION_REQUEST';
export const DELETE_CONFIGURATION_SUCCESS = 'App/DELETE_CONFIGURATION_SUCCESS';
export const DELETE_CONFIGURATION_FAILURE = 'App/DELETE_CONFIGURATION_FAILURE';

export const CREATE_UPDATE_USER_RESET = 'App/CREATE_UPDATE_USER_RESET';

export const SIGN_OUT = 'App/SIGN_OUT';