<?php
/**
 * @author     Martin Høgh <mh@mapcentia.com>
 * @copyright  2013-2022 MapCentia ApS
 * @license    http://www.gnu.org/licenses/#AGPL  GNU AFFERO GENERAL PUBLIC LICENSE 3
 *
 */

namespace app\inc;

use app\models\Geofence;
use Exception;
use sad_spirit\pg_builder\Delete;
use sad_spirit\pg_builder\Insert;
use sad_spirit\pg_builder\Select;
use sad_spirit\pg_builder\Update;
use sad_spirit\pg_builder\BlankWalker;


class TableWalkerRule extends BlankWalker
{
    private $rules;

    /**
     * @throws Exception
     */
    public function walkSelectStatement(Select $statement)
    {
        foreach ($statement->from->getIterator() as $from) {
            $schema = $from->name->schema->value ?? "public";
            $relation = $from->name->relation->value;
            $userFilter = new UserFilter("silke", "sql", "get", "*", $schema, $relation);
            $geofence = new Geofence($userFilter);
            $response = $geofence->authorize($this->rules);
            if (!empty($response["filters"]["read"])) $statement->where->and($response["filters"]["read"]);
        }
        parent::walkSelectStatement($statement);
    }

    public function walkUpdateStatement(Update $statement)
    {
        foreach ($statement->from->getIterator() as $from) {
            $schema = $from->name->schema->value ?? "public";
            $relation = $from->name->relation->value;
            $userFilter = new UserFilter("silke", "sql", "get", "*", $schema, $relation);
            $geofence = new Geofence($userFilter);
            $response = $geofence->authorize($this->rules);
            if (!empty($response["filters"]["read"])) $statement->where->and($response["filters"]["read"]);
        }
        $schema = $statement->relation->relation->schema->value ?? "public";
        $relation = $statement->relation->relation->relation->value;
        $userFilter = new UserFilter("silke", "sql", "get", "*", $schema, $relation);
        $geofence = new Geofence($userFilter);
        $response = $geofence->authorize($this->rules);
        if (!empty($response["filters"]["read"])) $statement->where->and($response["filters"]["read"]);
        parent::walkUpdateStatement($statement);
    }

    public function walkDeleteStatement(Delete $statement): void
    {
        foreach ($statement->using->getIterator() as $using) {
            $schema = $using->name->schema->value ?? "public";
            $relation = $using->name->relation->value;
            $userFilter = new UserFilter("silke", "sql", "get", "*", $schema, $relation);
            $geofence = new Geofence($userFilter);
            $response = $geofence->authorize($this->rules);
            if (!empty($response["filters"]["read"])) $statement->where->and($response["filters"]["read"]);
        }
        parent::walkDeleteStatement($statement);
    }

    public function walkInsertStatement(Insert $statement)
    {
        $schema = $statement->relation->relation->schema->value ?? "public";
        $relation = $statement->relation->relation->relation->value;
        $userFilter = new UserFilter("silke", "sql", "get", "*", $schema, $relation);
        $geofence = new Geofence($userFilter);
        $response = $geofence->authorize($this->rules);
        if (!empty($statement->onConflict) && !empty($response["filters"]["read"])) $statement->onConflict->where->and($response["filters"]["read"]);
        parent::walkInsertStatement($statement); // TODO: Change the autogenerated stub
    }

    public function setRules(array $rules): void
    {
        $this->rules = $rules;
    }
}
