<?php

namespace app\inc;

use sad_spirit\pg_builder\Delete;
use sad_spirit\pg_builder\Insert;
use sad_spirit\pg_builder\Select;
use sad_spirit\pg_builder\Update;
use sad_spirit\pg_builder\BlankWalker;


class TableWalkerRule extends BlankWalker
{
    public function walkSelectStatement(Select $statement)
    {
        foreach ($statement->from->getIterator() as $from) {
            //print($from->name->relation->value);
            $statement->where->and("userid='SELECT'");
        }
        parent::walkSelectStatement($statement);
    }

    public function walkUpdateStatement(Update $statement)
    {
        //print_r($statement->relation->relation->relation->value);
        $statement->where->and("userid='UPDATE'");
        parent::walkUpdateStatement($statement);
    }

    public function walkDeleteStatement(Delete $statement): void
    {
        foreach ($statement->using->getIterator() as $using) {
            //$using->name->relation->value
            $statement->where->and("userid='USING'");
        }
        $statement->where->and("userid='DELETE'");
        parent::walkDeleteStatement($statement);
    }

    public function walkInsertStatement(Insert $statement)
    {
        //print_r($statement->relation->relation->relation->value);
        if (!empty($statement->onConflict)) $statement->onConflict->where->and("userid='INSERT'");
        parent::walkInsertStatement($statement); // TODO: Change the autogenerated stub
    }
}
