<?php
header("Content-type: image/png");
function microtime_float()
{
    list($utime, $time) = explode(" ", microtime());
    return ((float)$utime + (float)$time);
}
include("../../inc/user_name_from_uri.php");
include("inc/bgmaps.php");
//$postgisschema = $parts[5];
$postgisschema = "kommuneplan";
$postgisdb = $parts[4];

$startTime = microtime_float();
include_once("../../conf/main.php"); 
include_once '../../libs/PEAR/Cache_Lite/Lite.php';
$id = $_SERVER['SCRIPT_FILENAME'].$_SERVER['PHP_SELF'].$_SERVER['QUERY_STRING'];
$options = array('cacheDir' => "{$basePath}/tmp/", 'lifeTime' => 0);
$Cache_Lite = new Cache_Lite($options);
if ($data = $Cache_Lite->get($id)) {} 
else {
	ob_start();
	/*if($_REQUEST['width'] && $_REQUEST['height'])
	{
		$width = $_REQUEST['width'];
		$height = $_REQUEST['height'];
	
	}
	else {*/
		if (!empty($bgmapSizes[$postgisdb])) {
			$width = $bgmapSizes[$postgisdb]['x'];
			$height = $bgmapSizes[$postgisdb]['y'];
		}
	//}
	//echo $_GET['extent']."<br>";
	include ("functions.php");
	$units = "xy";
	$controlObject = new control(true,false);
	$extentArr = explode(",",$_GET['extent']);
	$controlObject->minx=$extentArr[0];
	$controlObject->miny=$extentArr[1];
	$controlObject->maxx=$extentArr[2];
	$controlObject->maxy=$extentArr[3];
	$controlObject->setproportion();
	
	$extent = $controlObject->getExtentAsStr();
	//echo $extent;
	
	$layerArr = explode(";",$_REQUEST['layer']);

	foreach ($layerArr as $layer) {
		$bits = explode(",",$layer);
		if ($layer) {
			$wmsLayersArr[] = $bits[0];
		}
	}
	$wmsLayersStr = implode(",",$wmsLayersArr);
	$bgmap = $bgmaps[$postgisdb];
	if (!$bgmap) {
		$bgmap = "public.kms_skaermkort";
	}
	$mapUrl="{$hostName}/wms/{$postgisdb}/{$postgisschema}/?LAYERS={$bgmap},{$wmsLayersStr}&TRANSPARENT=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A900913&BBOX={$extent}&WIDTH={$width}&HEIGHT={$height}";
	$im=imagecreatefrompng($mapUrl);
	imagepng($im);
	imagedestroy($im);
	
	// Cache script
	$data = ob_get_contents();
	$Cache_Lite->save($data, $id);
	ob_get_clean();
}
echo $data;

