<html>
<head>
<title>MyGeoCloud - Online GIS - Store geographical data and make online maps - WFS and WMS</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
.layer_text {
	font-weight: normal;
	color: #545454;
	text-align: left;
}

a:link {
	color: #545454;
}

a:visited {
	color: #545454;
}

body {
	font-family: verdana, arial, helvetica, sans-serif;
	font-size: 11;
	margin: 0px;
	padding: 0px;
}
</style>

<script type="text/javascript" src="/js/jquery/1.6.4/jquery.min.js">
		</script>

<script type="text/javascript" src="/js/ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/ext/ext-all.js"></script>
<link rel="stylesheet" type="text/css"
	href="/js/ext/resources/css/ext-all.css" />


<script>
	

var str = "<?php echo $_REQUEST["layers"];?>";
var arr = str.split(";");
var lat;
var lon;
var defaultLayers = "";
function loadLayer(i,name,title,table,opacity,connectionString,e){
	var newArr = [];
 	//parent.mapframe.popupOn = true;
	//alert (e.checked);
	if (e.checked) {
		parent.mapframe.addLayer(name,title,opacity,connectionString);
		arr[i] = name;
	}
	else {
		parent.mapframe.removeLayer(name);
		arr.splice(i,1,0);
	}
	str = parent.mapframe.trim(arr.join(";"));
	parent.mapframe.layerStr = str + defaultLayers;
	parent.mapframe.addLegend(str + defaultLayers);

}
function addEmbedStr() {
var lonLat = parent.mapframe.map.getCenter();
var embedStr1 = '<div class="mapdivopen"><iframe scrolling="no" style="width: 100%; height: 100%;" src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/kortbrowser/appformap/openlayers.phtml?layers=' + str + defaultLayers  + '&lon=' + lonLat.lon + '&lat=' + lonLat.lat + '&zoom=' + parent.mapframe.map.getZoom() + '&lan=<?php echo $_REQUEST["lan"];?>&location=' + parent.locationframe.$('#locationSelector').val() + '" frameborder="0"></iframe></div>';
	
	
	var mapBounds = parent.mapframe.map.getExtent();
	var boundsArr =  mapBounds.toArray();
	var boundsStr =  boundsArr.join(",");
	var mapSize = parent.mapframe.map.getSize();
	
	var embedStr2 = '<div class="mapdivstat" style="display:none"><img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/kortbrowser/appformap/client_image.phtml?extent='+boundsStr+'&width='+mapSize.w+'&height='+mapSize.h+'&layer='+str+defaultLayers+'&lan=<?php echo $_REQUEST["lan"];?>&location=' + parent.locationframe.$('#locationSelector').val() + '"/></div>';
	
	var embedStr3 = '<div class="legenddivstat" style="display:none"><img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/kortbrowser/appformap/legend_img.phtml?layer='+str+defaultLayers+'&lan=<?php echo $_REQUEST["lan"];?>"/></div>';
	
	var embedStr4 = 'http://<?php echo $_SERVER['SERVER_NAME']; ?>/kortbrowser/appformap/openlayers.phtml?layers=' + str + defaultLayers  + '&lon=' + lonLat.lon + '&lat=' + lonLat.lat + '&zoom=' + parent.mapframe.map.getZoom() + '&lan=<?php echo $_REQUEST["lan"];?>&location=' + parent.locationframe.$('#locationSelector').val();
	
	document.getElementById('embed_area1').value = embedStr1+embedStr2+embedStr3;
	document.getElementById('embed_area4').value = embedStr4;
}
var items = [];

</script>
</head>
<body class="claro">

<?php
include("inc/uri_parts.php");
ini_set("display_errors", "On");
error_reporting(3);

include("inc/uri_parts.php");
$postgisschema = $parts[5];
$postgisdb = $parts[4];



$doNotLoadArr = array();

include_once("../../conf/main.php");
include_once("libs/functions.php");
include("model/tables.php");
include("controller/wmslayers_c.php");

$i = 0;
foreach($responseWmsLayers['data'] as $arr) {
	if ($arr['f_table_schema']==$postgisschema) {
		if ($arr['f_table_title']) {
			$titles[$arr['f_table_name']] = $arr['f_table_title'];
		}
		else {
			$titles[$arr['f_table_name']] = $arr['f_table_name'];
		}
		if ($arr['layergroup']) {
			$groups[$arr['f_table_name']] = $arr['layergroup'];	
		}
		else {
			$groups[$arr['f_table_name']] = "Default group";
		}
	}
}
//print_r($groups);
//asort($titles);
?>
<script>
<?php
foreach (array_unique($groups) as $group)
{?>
items.push({
	xtype: 'panel',
	title: '<?php echo $group;?>',
	bodyStyle: {padding: '5px'},
	collapsible: true,
    html: "<div><?php	
	echo "<div  title='{$group}'>";
	foreach($titles as $layer=>$title)
	{
		foreach($responseWmsLayers['data'] as $arr) {
			if ($arr['f_table_name']==$layer) {
				$layer = $postgisschema.".".$layer;
				//$table = $layerObj -> getMetaData("query_table");
				$abstract = $arr['f_table_abstract'];
				$href = $arr['meta_url'];
				if (!$arr['layergroup']) {
					$arr['layergroup'] = "Default group";
				}
				$layerGroup = $arr['layergroup'];
				$opacity = 1;
				if (!$_table) $_table = $layer;
				if ($layerGroup == $group && ($layerGroup)) {
					if ($arr['baselayer']!="t") {
					    $st = postgis::explodeTableName($layer);
						$layerConnectionString = "{$hostName}/wms/{$postgisdb}/{$st["schema"]}/";
						echo "<input class='layer' type='checkbox' name='{$layer}' id='{$layer}' onclick='javascript:loadLayer({$i},\\\"{$layer}\\\",\\\"{$title}\\\",\\\"{$_table}\\\",\\\"{$opacity}\\\",\\\"{$layerConnectionString}\\\",this)'";
						if (in_array($layer,explode(";",$_REQUEST["layers"]))) echo " CHECKED";		
						echo "/>";
						
						if ($abstract) {
							$class="class='tooltip' id='tt{$layer}'";
						}
						else {
							$class = "";
						}
						$titleStr = "<span ".$class.">".$title."</span>";
						if ($href) {
							echo "<a target='_blank' href='".$href."'>".$titleStr."</a>";
						}
						else {
							echo $titleStr;
						}
						echo "<br/>";
					}
				}
				$i++;
			}
		}
	}
echo "</div>";
echo "</div>\"})\n";
}
?>
   
new Ext.Viewport({
        //cls: 'x-layout-grid',
        autoScroll: true,
        items: items
    });


</script>
<br />
<br />
<div style="bottom:0px;display:<?php if ($_REQUEST['showcodebox']) {echo "inline";} else {echo "none";}?>;">
<form id="theForm" name="theForm">
<div>Interaktivt- og statisk kort</div>
<input type="text" size="30" id="embed_area1" name="embed_area1"
	onclick="javascript:document.theForm.embed_area1.focus();document.theForm.embed_area1.select();"
	readonly='readonly' />
<div>Url til kort</div>
<input type="text" size="30" id="embed_area4" name="embed_area4"
	onclick="javascript:document.theForm.embed_area4.focus();document.theForm.embed_area4.select();"
	readonly='readonly' /> <br />
<a href="#" id="codeButton">Se kode</a><br />
</form>
</div>
</body>
</html>
