<?php
include("../../conf/main.php");
include("inc/uri_parts.php");
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style type="text/css">
    html, body { width: 100%; height: 100%; margin: 0; overflow:hidden; }
    #borderContainer { width: 100%; height: 100%; }
</style>

	<script type="text/javascript" src="/js/ext/adapter/ext/ext-base.js"></script>
        <script type="text/javascript" src="/js/ext/ext-all.js"></script>
        <link rel="stylesheet" type="text/css" href="/js/ext/resources/css/ext-all.css" />

</head>
<body>

	<div id="layers">

		<!--<iframe name="locationframe" scrolling="no" frameborder="0" style="WIDTH: 100%; HEIGHT:30px" src="/apps/viewer/includes/location_select.php?lan=da&location=<?php echo $_REQUEST["location"];?>&showcodebox=<?php echo $_REQUEST["showcodebox"];?>"></iframe><br/>-->

		<iframe scrolling="no" id="layerframe" frameborder="0" style="WIDTH: 100%; HEIGHT: 100%" src="/apps/viewer/layer_loader/<?php echo $parts[4];?>/<?php echo $parts[5];?>?lan=da&<?php echo $_SERVER['QUERY_STRING'];?>"></iframe>

	</div>
	<div id="main">

		<iframe scrolling="no" frameborder="0" id="mapframe" name="mapframe"  style="WIDTH: 100%; HEIGHT: 100%" src="/apps/viewer/openlayers/<?php echo $parts[4];?>/<?php echo $parts[5];?>?lan=da&usepopup=false&popup=true&filter=<?php echo urldecode($_REQUEST['filter']);?>"></iframe>
	</div>
</body>
<script type="text/javascript">
    Ext.onReady(function(){
	       var viewport = new Ext.Viewport({
            layout:'border',
            items:[{
                region:'west',
                id:'west-panel',
                split:true,
                width: 250,
                minSize: 175,
                maxSize: 400,
                collapsible: false,
                margins:'5 0 5 5',
                cmargins:'5 5 5 5',
                layoutConfig:{
                    animate:true
                },
                contentEl:document.getElementById("layers")
            },{
                region:'center',
                margins:'5 5 5 0',
                layout:'column',
                autoScroll:false,
		border: false,
                contentEl:document.getElementById("main")
                }]
        });
    });
	</script>
</html>
