<?php
//print_r($_REQUEST);
session_start();
function microtime_float()
{
	list($utime, $time) = explode(" ", microtime());
	return ((float)$utime + (float)$time);
}
$startTime = microtime_float();

include("../../libs/functions.php");
include("../../inc/user_name_from_uri.php");
$postgisschema = $parts[5];
$postgisdb = $parts[4];

if ($parts[4]=="rebild" /*&& (!$_GET['mapframe'])*/){
	if (!$_GET['lon']){
		$_GET['lon']=0;
		$_GET['lat']=0;
		
	}
	if (!$_GET['srs']) {
		$_GET['srs'] = "EPSG:900913";
	}
	die("
	    <script type=\"text/javascript\" src=\"http://mygeocloud.cowi.webhouse.dk/js/openlayers/proj4js-combined.js\"></script>
		<script type=\"text/javascript\" src=\"http://mygeocloud.cowi.webhouse.dk/js/openlayers/defs/EPSG900913.js\"></script>
		<script type=\"text/javascript\" src=\"http://mygeocloud.cowi.webhouse.dk/js/openlayers/defs/EPSG25832.js\"></script>
		<script type=\"text/javascript\">
		try{
		function transformPoint(lat,lon,s,d) {
			var source = new Proj4js.Proj(s);    //source coordinates will be in Longitude/Latitude
			var dest = new Proj4js.Proj(d);
			var p = new Proj4js.Point(lat,lon);
			Proj4js.ST_Transform(source, dest, p);
		   return p;
		}
		var p = transformPoint({$_GET['lon']},{$_GET['lat']},'{$_GET['srs']}','EPSG:25832');
		//alert(p.y + ' ' +p.x);
		window.location = \"http://mygeocloud.cowi.webhouse.dk/apps/viewer/openlayers_test/rebild?{$_SERVER['QUERY_STRING']}&lat=\"+p.y+\"&lon=\"+p.x;
		}
		catch(e){}
		</script>
	");
};

include("../../libs/FirePHPCore/FirePHP.class.php");
include("../../libs/FirePHPCore/fb.php");
include("../../conf/main.php");
include("../../wfs/explodefilter.php");
include("../../libs/PEAR/XML/Unserializer.php");
include("../../libs/PEAR/XML/Serializer.php");
$srs = "900913";
$postgisObject = new postgis(); 

include '../../model/settings_viewer.php';
$settingsViewer = new Settings_viewer();
$settingsViewer = $settingsViewer->get(true);// move to a controller
include("../../model/tables.php");
include("controller/wmslayers_c.php");
?>
<html>
<head>
<title>MyGeoCloud - Online GIS - Store geographical data and make online maps - WFS and WMS</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<style type="text/css">
#map {
	width: 100%;
	height: 100%;
	position: absolute;
	top: 0px;
	left: 0px;
	z-index: 1;
}
body {
	margin: 0px;
	padding: 0px;
}
#legend {
	padding: 0px;
	position: absolute;
}
</style>
<link rel="stylesheet" type="text/css" href="/js/ext/resources/css/ext-all.css" />
<link rel="stylesheet" type="text/css" href="/js/ext/resources/css/xtheme-gray.css" />
<link rel="stylesheet" type="text/css" href="/styles/styles.css" />


<script type="text/javascript" src="/js/jquery/1.6.4/jquery.min.js"></script>



<script type="text/javascript">
//<![CDATA[
		var layer;
		var newLayerStrArr = [];
		var map,layer,popup,markers;
		var conf=[];
		var MapappWin = null;
		var popupOn = <?php  if ($_REQUEST['popup']) echo $_REQUEST['popup']; else echo "1";?>;
		//var popupOn = false;
		var base = [];
		var usepopup = '<?= $_REQUEST['usepopup'] ?>';
		var layerStr = '<?= $_REQUEST['layers'] ?>';
		var graphicLayer;
		var renderGeometryArray;
		var resultHtml = "";
		var minxFromFilter=0;
		var minyFromFilter=0;
		var maxxFromFilter=0;
		var maxyFromFilter=0;
        var autocomplete; 
        var placeMarkers;
        var placePopup;
		var restrictedBounds;
		var viewPortSize;
		var settingsViewer = <?php echo json_encode($settingsViewer['data']); ?>;// JSON;
		 
		//OpenLayers.ImgPath = "/js/openlayers/theme/dark/";
		
		if (!settingsViewer.minzoomlevel) {
			settingsViewer.minzoomlevel = 1;
		};
		if (!settingsViewer.maxzoomlevel) {
			settingsViewer.maxzoomlevel = 20;
		};
		//console.log(settingsViewer);
		function osm_getTileURL(bounds) {
            var res = this.map.getResolution();
            var x = Math.round((bounds.left - this.maxExtent.left) / (res * this.tileSize.w));
            var y = Math.round((this.maxExtent.top - bounds.top) / (res * this.tileSize.h));
            var z = this.map.getZoom();
            var limit = Math.pow(2, z);
 
            if (y < 0 || y >= limit) {
                return OpenLayers.Util.getImagesLocation() + "404.png";
            } else {
                x = ((x % limit) + limit) % limit;
                return this.url + z + "/" + x + "/" + y + "." + this.type;
            }
        }
		if ($("html").width()>300) {
			viewPortSize = "big";
		}
		else {
			viewPortSize = "small";
		}
<?php
$_REQUEST['signaturoff']="true";

if ($_REQUEST['popuppage']) {
    $popupPage = $_REQUEST['popuppage'];
}
else {
    $popupPage = $_SERVER['PHP_SELF'];
}

/* SET FILTER */

function array_map_r($arr)
{
    global $filterArr;
    //global $namedLayer;
	//print_r($arr);
    foreach( $arr as $key => $value )
    {
		if (is_array($value['Filter'])) $filterArr = $value['Filter']; 
        if ( is_array( $value ))  array_map_r( $value );
    }  
}

if ($_REQUEST['sld'])
{
	$unserializer_options = array ('parseAttributes' => TRUE,'typeHints' => FALSE);
	$unserializer = new XML_Unserializer($unserializer_options);
	$status = $unserializer->unserialize(urldecode($_REQUEST['sld']));
	$sldArr = $unserializer->getUnserializedData();
	array_map_r($sldArr);
	if ($_REQUEST['overRideNamedLayerWith']) {
		$sldArr['NamedLayer']['Name'] = $_REQUEST['overRideNamedLayerWith'];
	}
	$filter = parseFilter($filterArr,$sldArr['NamedLayer']['Name']);
	$query = "SELECT ST_Xmin(ST_Extent(ST_Transform(linestring,{$srs}))) as minx, ST_Ymin(ST_Extent(ST_Transform(linestring,{$srs}))) as miny, ST_Xmax(ST_Extent(ST_Transform(linestring,{$srs}))) as maxx, ST_Ymax(ST_Extent(ST_Transform(linestring,{$srs}))) as maxy FROM {$sldArr['NamedLayer']['Name']} WHERE ".$filter;
	echo "<!-- TEST {$query} -->\n";
	$result = $postgisObject -> execQuery($query);
	$row = $postgisObject->fetchRow($result);
	$buffer = 100;
	if ($row[minx]) {
		echo "minxFromFilter = ".($row[minx]-$buffer).";\n";
		echo "maxxFromFilter = ".($row[maxx]+$buffer).";\n";
		echo "minyFromFilter = ".($row[miny]-$buffer).";\n";
		echo "maxyFromFilter = ".($row[maxy]+$buffer).";\n";
		$extentSetFromFilter = true;
	}
}
/* SET FILTER END */
if ((!$_REQUEST['lat']) || (!$_REQUEST['lon']))
{
    $_REQUEST['lon'] = $openLayers['center']['lon'];
    $_REQUEST['lat'] = $openLayers['center']['lat'];
}
if (!$_REQUEST['zoom'])
{
    $_REQUEST['zoom'] = $openLayers['zoom'];
    if ((!$_REQUEST['zoom']))
    {
	$_REQUEST['zoom']="0";
    } 
}
$openLayers['bounds'] = str_replace(" ",",",$openLayers['bounds']);
$openLayers['restricted'] = str_replace(" ",",",$openLayers['restricted']);


$layers = explode(";",$_REQUEST['layers']);
$u=0;
for($i = 0; $i < sizeof($layers); $i++){
	$bits = explode(",",$layers[$i]);
	$st = postgis::explodeTableName($bits[0]);
	foreach($responseWmsLayers['data'] as $arr) {
		if ($arr['f_table_name']==$st['table'] && $arr['f_table_schema']==$st['schema']) {
			echo "conf[$u] = ['{$bits[0]}','{$bits[1]}']\n";
			echo "conf[$u][2] ='".$arr['appformap_opacity']."'\n";
			echo "conf[$u][3] ='".$arr['f_table_title']."'\n";
			echo "conf[$u][4] ='".$bits[1]."'\n";
			
			
			$layerConnectionString = "http://{$_SERVER['HTTP_HOST']}/wms/{$postgisdb}/{$st['schema']}/";
			if ($arr['tilecache']) {
				$layerConnectionString.="tilecache/"; 
			}
			echo "conf[$u][5] ='{$layerConnectionString}/'\n";
			echo "conf[$u][6] ='".$arr['single_tile']."'\n";
			
				// Only default visible layers i layerStr
			if (!$bits[1]) {
				echo "newLayerStrArr.push('{$bits[0]}');\n";
			}
			$u++;
		}
	}
}
// Set extent from layer
if(!$extentSetFromFilter) {
$table = $settingsViewer['data']['default_extent'];
$geomField = $postgisObject->getGeometryColumns("public.".$table,"f_geometry_column");
if ($geomField) {
	$sql = "SELECT ST_Xmin(ST_Extent(ST_Transform(".$geomField.",$srs))) AS TXMin,ST_Xmax(ST_Extent(ST_Transform(".$geomField.",$srs))) AS TXMax, ST_Ymin(ST_Extent(ST_Transform(".$geomField.",$srs))) AS TYMin,ST_Ymax(ST_Extent(ST_Transform(".$geomField.",$srs))) AS TYMax  FROM public.".$table;
	$result = $postgisObject->execQuery($sql);
	$row = $postgisObject->fetchRow($result);
	
		echo "minxFromFilter = ".($row[txmin]-$buffer).";\n";
		echo "maxxFromFilter = ".($row[txmax]+$buffer).";\n";
		echo "minyFromFilter = ".($row[tymin]-$buffer).";\n";
		echo "maxyFromFilter = ".($row[tymax]+$buffer).";\n";
	
}
else {
	
	echo "minxFromFilter = -20037508;";
	echo "maxxFromFilter = 20037508;";
	echo "minyFromFilter = -20037508;";
	echo "maxyFromFilter = 20037508;";
}
}
print_r($postgisObject->PDOerror);
// End setting extent from layer

?>
//console.log(conf);


    var layerArr =[]
    function addLayer(name,title,opacity,connectionString,notVisible,singleTile) {
        var enableTileCache = false;
        if (notVisible) {
            var visible = false;
        }
        else {
            var visible = true;
        }
        if (!singleTile || singleTile=="f"){
        	singleTile=false;
        }
        if (enableTileCache) {
        	connectionString = connectionString + "tilecache/";
        }
        layerArr[name] = new OpenLayers.Layer.WMS(title,connectionString + "?SLD_BODY=<?php echo urlencode($_REQUEST['sld'])?>&",{layers:name,transparent:true},{buffer:0,singleTile:singleTile,opacity:opacity,isBaseLayer:false,visibility:visible,wrapDateLine:false});
		
        map.addLayer(layerArr[name]);
    }
   
       
    function deserialize(element) {
			
            var type = "wkt";
			var format = new OpenLayers.Format.WKT;
            var features = format.read(element);
            var bounds;
            if(features) {
                if(features.constructor != Array) {
                    features = [features];
                }
                for(var i=0; i<features.length; ++i) {
                    if (!bounds) {
                        bounds = features[i].geometry.getBounds();
                    } else {
                        bounds.extend(features[i].geometry.getBounds());
                    }
 
                }
                vectors.addFeatures(features);
                //map.zoomToExtent(bounds);
                var plural = (features.length > 1) ? 's' : '';
                element = features.length + ' feature' + plural + ' added';
            } else {
                element = 'Bad input ' + type;
            }
        }
   

    function removeLayer(name){
        map.removeLayer(layerArr[name]);
    }
    function removeAllLayers(){
        for(var i in layerArr) {
            var value = layerArr[i];
            if (i!="kommunegrs") map.removeLayer(value);
        }
    }
    function addLegend(layers) {
		var param = 'layers=' + layers + '&amp;type=text&amp;lan=<?php echo $_REQUEST["lan"];?>';
		$.ajax({
        url: '/apps/viewer/servers/legend/<?php echo $postgisdb;?>?' + param,
        async: false,
        dataType: 'json',
        type: 'GET',
        success: function (data, textStatus, http) {
				if (http.readyState == 4) {
					if (http.status == 200) {
						var response = eval('(' + http.responseText + ')');
						// JSON
						//alert(response.html);
						$('#legendContent').empty();
						$('#legendContent').append(response.html);
					}
				}
			}
		});
		//$('#legendContent').load('/apps/viewer/servers/legend/<?php echo $postgisdb;?>?' + param);
		//document.getElementById("legendContent").innerHTML = "/apps/viewer/servers/legend/<?php echo $postgisdb;?>?" + param;
    }
    function trim(s) {
        s = s.replace(/(^\;*)|(\;*$)/gi,"");
        s = s.replace(/[;]{2,}/gi,";");
        //s = s.replace(/\n /,"\n");
        return s;
    }
    function printVersion()
    {
        var mapBounds = map.getExtent();
        var boundsArr =  mapBounds.toArray();
        var boundsStr =  boundsArr.join(",");
        var mapSize = map.getSize();
        document.printForm.renderGeometryArray.value = renderGeometryArray;
        document.printForm.extent.value = boundsStr;
        document.printForm.width.value = mapSize.w;
        document.printForm.height.value = mapSize.h;
        document.printForm.layer.value = layerStr;
        document.printForm.resultHtml.value = resultHtml;
        document.printForm.bgMap.value = map.baseLayer.name;
		document.printForm.location.value = "<?php echo $_REQUEST["location"];?>";
		document.printForm.lan.value = "<?php echo $_REQUEST["lan"];?>";
        document.printForm.action="print.phtml";
        document.printForm.target="blank";
        document.printForm.submit();
        document.printForm.target="";
        document.printForm.action="<? echo $_SERVER['PHP_SELF']; ?>";
    }
	function openMapWin(page,width,height)
	{
		var iLangID = iLangID;
		var iWidth 					= width;
		var iHeight 				= height;
		var strWinName = "MapServer";
		var strURL = page;
		var popleft = (screen.width - iWidth) / 2;
		var poptop = (screen.height - iHeight) / 2;
		
		var strParameters 	= "width=" + iWidth + ",height=" + iHeight + 
							",resizable=1,scrollbars=0,status=1,left="+
							popleft+",top="+poptop+",screenX="+popleft+
							",screenY="+poptop+",toolbar=0";

		if (MapappWin == null) openWin = true;
		else if (MapappWin.closed) openWin = true;
		else openWin = false;
		
		if (openWin) {
			MapappWin 	= window.open(strURL, strWinName, strParameters);
			MapappWin.focus();
		} else {
			if (!MapappWin.closed) {
				MapappWin.focus();
			}
		}
	}
	function inFrames()
	{
		return ( top != self );
	}
	function checkFrameId()
	{
		return (window.parent.getElementById('mapframe'));
	}
	//alert(checkFrameId());
	function createPointFromStr(str){
		var coordArr = str.split(" ");
		var point = new OpenLayers.Marker(new OpenLayers.LonLat(points1[0],points1[1]));
		return point;
	}

	// We need to use jQuery load function to make sure that document.namespaces are ready. Only IE
	$(window).load(function(){
	   
		var legendWin;
		var searchWin;
		var embedWin;
	restrictedBounds = new OpenLayers.Bounds(minxFromFilter,minyFromFilter,maxxFromFilter,maxyFromFilter);
    layerStr = trim(newLayerStrArr.join(";"));
    OpenLayers.Control.Click = OpenLayers.Class(OpenLayers.Control, {
        defaultHandlerOptions: {
            'single': true,
            'double': false,
            'pixelTolerance': 0,
            'stopSingle': false,
            'stopDouble': false
        },

        initialize: function(options) {
            this.handlerOptions = OpenLayers.Util.extend(
            {}, this.defaultHandlerOptions
        );
            OpenLayers.Control.prototype.initialize.apply(
            this, arguments
        );
            this.handler = new OpenLayers.Handler.Click(
            this, {
                'click': this.trigger
            }, this.handlerOptions
        );
        },
        trigger: function(e) {
        	if (popupOn) {
			var mapBounds = map.getExtent();
			var boundsArr =  mapBounds.toArray();
			var boundsStr =  boundsArr.join(",");
			var coords = map.getLonLatFromViewPortPx(e.xy);
			try {popup.destroy()} catch(e){};
			popup = new OpenLayers.Popup.FramedCloud("result",coords,null,"<div id='queryResult' style='z-index:1000;width:300px;height:100px;overflow:auto'>Wait..</div>",null, true);
			map.addPopup(popup)
			mapSize = map.getSize();
			Ext.Ajax.request({
                            url: '/apps/viewer/servers/query/<?php echo $postgisdb;?>/<?php echo $postgisschema;?>',
                            headers: {
                                //'Content-Type': 'application/json; charset=utf-8'
                            },
                            params: 'lan=<?php echo $_REQUEST["lan"];?>&proj=<?php echo $srs; ?>&lon=' + coords.lon + '&lat=' + coords.lat + '&layers=' + layerStr + '&type=json&extent=' + boundsStr + '&width=' + mapSize.w + '&height=' + mapSize.h,
                            success: function(http) {
		if (http.status == 200) {
			var response = eval('(' + http.responseText + ')');// JSON
			if (response.html!=false) {
				document.getElementById("queryResult").innerHTML=response.html;
				resultHtml = response.html; // Global var
			}
			else {
				document.getElementById("queryResult").innerHTML= "Found nothing";
			}
			//addGraphicLayer("Resultat",response.overlayMapimageUrl,response.extent);
			vectors.removeAllFeatures();
			map.raiseLayer(vectors,10);
			for ( var i=0; i<response.renderGeometryArray.length; ++i ){
				deserialize(response.renderGeometryArray[i][0]);
				}
			renderGeometryArray = response.renderGeometryArray; // Global var
		}
	}
                            //failure: test
                        });
		}
	}
    });

	//if ((!inFrames()) || (doNotUsePopUp=='false')) document.getElementById("popupButton").style.display = "none";
	function mapLayerChanged(event) {
            var newlayerArr =[];
            layerStrArr = layerStr.split(";");
            for (var i in layerArr) {
                if (layerArr[i] == event.layer) {
                    layer = i;
                }
            }
            if (layer) {
                if (!event.layer.visibility) {
                    for (i=0;i<layerStrArr.length;i++)
                    {
                        if (layerStrArr[i]==layer) var key = i;
                    }
                    layerStrArr.splice(key,1);
                    key = null;
                }
                if (event.layer.visibility) {
                    layerStrArr.push(layer);
                }
                layerStr = trim(layerStrArr.join(";"));
                //alert(layerStr);
                addLegend(layerStr);
                layer = null;
            }
        }
		if (viewPortSize=="big"){
			var mapControls = [
				new OpenLayers.Control.PanZoomBar(),
				//new OpenLayers.Control.ScaleLine(),
				new OpenLayers.Control.LayerSwitcher(),
				new OpenLayers.Control.Navigation({'zoomWheelEnabled': false})
			];
		}
		else {
			var mapControls = [
				new OpenLayers.Control.Navigation({'zoomWheelEnabled': false}),
				new OpenLayers.Control.LayerSwitcher()
			];
			mapControls = null;
		}
        map = new OpenLayers.Map(document.getElementById("mapel"),{
		controls:mapControls,
        numZoomLevels:20,
		projection: new OpenLayers.Projection("EPSG:<?php echo $srs;?>"),
		maxResolution: 156543.0339,
		units: "m",
		//minResolution: "auto",
        eventListeners: {"changelayer": mapLayerChanged}
		//tileSize: new OpenLayers.Size(512,512)
		}
        );
        
	map.maxExtent = new OpenLayers.Bounds.fromString("-20037508, -20037508, 20037508, 20037508");
	var base = [];
	// Add WMS baselayers
	<?php
	if ($parts[4]=="toender"){
		?>
			base.push(new OpenLayers.Layer.Google("Google Normal", {
			type: G_NORMAL_MAP,
			minZoomLevel: settingsViewer.minzoomlevel,
			maxZoomLevel: settingsViewer.maxzoomlevel,
			sphericalMercator: true
		}));
		base.push(new OpenLayers.Layer.WMS("KMS Sk&aelig;rmkort","http://beta.mygeocloud.cowi.webhouse.dk/wms/toender/public/",{layers:"public.kms_skaermkort",transparent:true},{buffer:0,singleTile:false,isBaseLayer:true,wrapDateLine:false,transitionEffect:'resize'}));
		
		base.push(new OpenLayers.Layer.WMS("Ortofoto 2010","http://beta.mygeocloud.cowi.webhouse.dk/wms/toender/public/",{layers:"public.orto_2010",transparent:true},{buffer:0,singleTile:false,isBaseLayer:true,wrapDateLine:false,transitionEffect:'resize'}));


		<?php
	}
	else{
	if (isset($responseWmsLayers['data'])){
	foreach($responseWmsLayers['data'] as $arr) {
		if ($arr['baselayer']) {
			$layerConnectionString = "http://{$_SERVER['HTTP_HOST']}/wms/{$postgisdb}/{$arr['f_table_schema']}/";
			if ($arr['tilecache']) {
				$layerConnectionString.="tilecache/"; 
			}
	?>
	
	base.push(new OpenLayers.Layer.WMS("<?php echo $arr['f_table_title'];?>","<?php echo $layerConnectionString;?>",{layers:"<?php echo $arr['f_table_schema'];?>.<?php echo $arr['f_table_name'];?>",transparent:true},{buffer:0,singleTile:false,isBaseLayer:true,wrapDateLine:false,transitionEffect:'resize'}));
	<?php }}}?>
	

	base.push(new OpenLayers.Layer.Google("Google Normal", {
		type: G_NORMAL_MAP,
		minZoomLevel: settingsViewer.minzoomlevel,
		maxZoomLevel: settingsViewer.maxzoomlevel,
		sphericalMercator: true
	}));
	base.push(new OpenLayers.Layer.Google("Google Hybrid", {
		type: G_HYBRID_MAP,
		minZoomLevel: settingsViewer.minzoomlevel,
		maxZoomLevel: settingsViewer.maxzoomlevel,
		sphericalMercator: true
	}));

	base.push(new OpenLayers.Layer.Google("Google Satellite", {
		type: G_SATELLITE_MAP,
		minZoomLevel: settingsViewer.minzoomlevel,
		maxZoomLevel: settingsViewer.maxzoomlevel,
		sphericalMercator: true
	}));

	base.push(new OpenLayers.Layer.Google("Google Terrain", {
		type: G_PHYSICAL_MAP,
		minZoomLevel: settingsViewer.minzoomlevel,
		maxZoomLevel: settingsViewer.maxzoomlevel,
		sphericalMercator: true
	}));

	base.push(new OpenLayers.Layer.TMS(
            "OpenStreetMap",
            "http://tile.openstreetmap.org/",
            {
                type: 'png', getURL: osm_getTileURL,
                displayOutsideMaxExtent: false,
                attribution: '<a href="http://www.openstreetmap.org/">OpenStreetMap</a>'
            }
        )
	);
	<?php } ?>


/*
	base.push(new OpenLayers.Layer.Bing("Bing road", {
		key: "Avt2oTtuFcQ2rzuy41B5DGydLYOxpgZaxuHkc4Ktgu6sG_6y-Ja6ncptoxbelYdx",
	    type: "Road"
	}));
*/

	
	
	vectors = new OpenLayers.Layer.Vector("Mark",{
			displayInLayerSwitcher: false
		});
 
            map.addLayers([vectors]);
			

        map.addLayers(base);
        
        
        //Start paa url zoom sdsd
		<?php
		if ($_REQUEST['bounds']) {
			$boundsArr = explode(",",$_REQUEST['bounds']); 
		?>
			var minxFromFilter = <?php echo $boundsArr[0];?>;
			var minyFromFilter = <?php echo $boundsArr[1];?>;
			var maxxFromFilter = <?php echo $boundsArr[2];?>;
			var maxyFromFilter = <?php echo $boundsArr[3];?>;
		<?php } ?> 
		//End paa url zoom

        
          var click = new OpenLayers.Control.Click();
        map.addControl(click);
        click.activate();
		
// Navigation history - two "button" controls
	var ctrl, toolbarItems = [], action, actions = {};
    ctrl = new OpenLayers.Control.NavigationHistory();
    map.addControl(ctrl);
   action = new GeoExt.Action({
        text: "Signatur",
	 handler:function(objRef){
		if(!legendWin){
		    legendWin = new Ext.Window({
			title: "Signatur",
			layout:'fit',
			width:200,
			height:300,
			closeAction:'hide',
			contentEl:legendContent,
			autoScroll: 'auto',
			x:5,
			y:120
		    });
		}
	    if(typeof(objRef)=="object"){
            legendWin.show(objRef);
        	}else{
            	legendWin.show();
        	}//end if object reference was passed
		
	    },
        tooltip: "Vis signatur"
    });

    toolbarItems.push(action);

    action = new GeoExt.Action({
        text: "Print",
        handler: printVersion,
        tooltip: "Print kortet"
    });

   action = new GeoExt.Action({
        text: "Find",
	 handler:function(objRef){
		if(!searchWin){
            $(".pac-container").css("z-index","10000"); // We make sure that Google auto complete is shown on top
		    searchWin = new Ext.Window({
			title: "Search",
			layout:'fit',
			width:300,
			height:70,
            plain: true,
			closeAction:'hide',
			contentEl:searchContent,
			x:5,
			y:120
		    });
		}
	    if(typeof(objRef)=="object"){
            searchWin.show(objRef);
        	}else{
            	searchWin.show();
        	}//end if object reference was passed
		
	    },
        tooltip: "Search"
    });
	toolbarItems.push(action);
<?php if ($_SESSION['auth']) {?>
	action = new GeoExt.Action({
        text: "Embed",
	 handler:function(objRef){
		if(!embedWin){
		    embedWin = new Ext.Window({
			title: "Embed",
			layout:'fit',
			width:300,
			height:300,
            plain: true,
			closeAction:'hide',
			contentEl:embedEl,
			x:5,
			y:120
		    });
		}
	    if(typeof(objRef)=="object"){
            embedWin.show(objRef);
        	}else{
            	embedWin.show();
        	}//end if object reference was passed
		
	    },
        tooltip: "Embed"
    });
    toolbarItems.push(action);
<?php }?>

	action = new GeoExt.Action({
        text: "Stort kort",
		handler:function(objRef){
		openMapWin('/apps/viewer/openlayers/<?php echo $postgisdb;?>?<?php echo $_SERVER['QUERY_STRING'];?>&layers='+layerStr,800,600)
		
	    },
        tooltip: "Stort kort"
    });
	

    if ((inFrames()) && usepopup!="false") toolbarItems.push(action);

    toolbarItems.push("->");
    action = new GeoExt.Action({
        text: "<<",
        control: ctrl.previous,
        disabled: true,
        tooltip: "previous in history"
    });

    toolbarItems.push(action);

    action = new GeoExt.Action({
        text: ">>",
        control: ctrl.next,
        disabled: true,
        tooltip: "next in history"
    });
    toolbarItems.push(action);

new Ext.Viewport({
        layout: "border",
        items: {
            region: "center",
            id: "mappanel",
            xtype: "gx_mappanel",
            map: map,
        tbar: toolbarItems 
        }
    });

	var mapPanel = Ext.getCmp("mappanel");

	if (minxFromFilter!=0) {
		map.zoomToExtent(restrictedBounds);
		<?php if (!$_REQUEST['sld']){
		 	echo "map.restrictedExtent = restrictedBounds;";
		 }?>
	};
	<?php if ($_REQUEST['lon'] && $_REQUEST['lat'] && $_REQUEST['zoom'] ) { ?>
	map.setCenter(new OpenLayers.LonLat(<?= $_REQUEST['lon'] ?>,<?= $_REQUEST['lat'] ?>), <?= $_REQUEST['zoom'] ?>);
	<?php }?>
	var p1 = transformPoint(minxFromFilter,minyFromFilter,"EPSG:<?php echo $srs;?>","EPSG:4326");
	var p2 = transformPoint(maxxFromFilter,maxyFromFilter,"EPSG:<?php echo $srs;?>","EPSG:4326");
	var defaultBounds = new google.maps.LatLngBounds(
	new google.maps.LatLng(p1.y,p1.x),
	new google.maps.LatLng(p2.y,p2.x)
);

var input = document.getElementById('gAddress');
var options = {
  bounds: defaultBounds
  //types: ['establishment']
};
var autocomplete = new google.maps.places.Autocomplete(input, options);
    //console.log(autocomplete.getBounds());

google.maps.event.addListener(autocomplete, 'place_changed', function() {
  var place = autocomplete.getPlace();
  //console.log(place);
  //console.log(place.geometry.location.lat());
 
  var p = transformPoint(place.geometry.location.lng(),place.geometry.location.lat(),"EPSG:4326","EPSG:<?php echo $srs;?>")
 var point = new OpenLayers.LonLat(p.x,p.y);
  map.setCenter(point,15);
try {placeMarkers.destroy()} catch(e){};
try {placePopup.destroy()} catch(e){};
placeMarkers = new OpenLayers.Layer.Markers( "Markers" );
map.addLayer(placeMarkers);

var size = new OpenLayers.Size(21,25);
var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
var icon = new OpenLayers.Icon('http://www.openlayers.org/dev/img/marker.png', size, offset);
placeMarkers.addMarker(new OpenLayers.Marker(point,icon));
placeMarkers.addMarker(new OpenLayers.Marker(point,icon.clone()));

placePopup = new OpenLayers.Popup.FramedCloud("place",point,null,"<div id='placeResult' style='z-index:1000;width:200px;height:50px;overflow:auto'>" + place.formatted_address + "</div>",null, true);
map.addPopup(placePopup)
	
  
});
for (var i=0; i<conf.length; i++) {
	if (conf[i][1]) {popupOn=true}
	if (conf[i][0]) {
	addLayer(conf[i][0],conf[i][3],conf[i][2],conf[i][5],conf[i][4],conf[i][6]);
	}
}
addLegend(layerStr);
$("#embedEl").show();
$("#searchContent").show();
});
function transformPoint(lat,lon,s,d) {
    var source = new Proj4js.Proj(s);    //source coordinates will be in Longitude/Latitude
    var dest = new Proj4js.Proj(d);
    var p = new Proj4js.Point(lat,lon);
    Proj4js.ST_Transform(source, dest, p);
   return p;
}
function addEmbedStr() {
	var lonLat = map.getCenter();
	var embedStr1 = '<div class="mygeocloud_frame"><iframe scrolling="no" style="width: 100%; height: 100%;" src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/apps/viewer/openlayers/<?php echo $postgisdb;?>?layers=' + layerStr + '&lon=' + lonLat.lon + '&lat=' + lonLat.lat + '&zoom=' + map.getZoom() + '&srs=' + map.projection + '" frameborder="0"></iframe></div>';
	 
	
	var mapBounds = map.getExtent();
	var boundsArr =  mapBounds.toArray();
	var boundsStr =  boundsArr.join(",");



	var mapSize = map.getSize();
	
	var embedStr2 = '<div class="mygeocloud_img" style="display:none"><img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/apps/viewer/image/<?php echo $postgisdb;?>/<?php echo $postgisschema;?>?extent='+boundsStr+'&width='+mapSize.w+'&height='+mapSize.h+'&layer='+layerStr+'"/>';
	
	var embedStr3 = '<div class="mygeocloud_legend" style="display:none">' + $('#legendContent').html() + '</div>';
	
	var embedStr4 = 'http://<?php echo $_SERVER['SERVER_NAME']; ?>/apps/viewer/openlayers/<?php echo $postgisdb;?>?layers=' + layerStr + '&lon=' + lonLat.lon + '&lat=' + lonLat.lat + '&zoom=' + map.getZoom() + '&srs=' + map.projection;
	
	document.getElementById('embed_area1').value = embedStr1+embedStr2+embedStr3;
	document.getElementById('embed_area4').value = embedStr4;
};
//]]>
</script>
</head>
<body>
<form name="printForm" id="printForm" method="post">
	<input type="hidden" name="extent"/>
	<input type="hidden" name="width" />
	<input type="hidden" name="height" />
	<input type="hidden" name="renderGeometryArray" />
	<input type="hidden" name="layer" />
	<input type="hidden" name="resultHtml" />
	<input type="hidden" name="bgMap" />
	<input type="hidden" name="location" />
	<input type="hidden" name="lan" />
	<input type="hidden" name="type" value="json" />
</form>
<div id="mapel"></div>
<div id="legendContent"></div>
<div style="display:none;padding: 5px" id="searchContent"><input style="width: 270px"
	type='text' id='gAddress' name='gAddress' value='' />
</div>
<div id="embedEl" style="display:none">
	<a href="javascript:void(0);" onclick="javascript:addEmbedStr();">Se kode</a><br/>
	<form id="theForm" name="theForm">
	<div>Interaktivt- og statisk kort</div>
	<input type="text" size="30" id="embed_area1" name="embed_area1" onclick="javascript:document.theForm.embed_area1.focus();document.theForm.embed_area1.select();" readonly='readonly' />
	<div>Interaktivt kort</div>
	<input type="text" size="30" id="embed_area2" name="embed_area2" onclick="javascript:document.theForm.embed_area2.focus();document.theForm.embed_area2.select();" readonly='readonly' />
	<div>Statisk kort</div>
	<input type="text" size="30" id="embed_area3" name="embed_area3" onclick="javascript:document.theForm.embed_area3.focus();document.theForm.embed_area3.select();" readonly='readonly' />
	<div>Url til kort</div>
	<input type="text" size="30" id="embed_area4" name="embed_area4" onclick="javascript:document.theForm.embed_area4.focus();document.theForm.embed_area4.select();" readonly='readonly' />
	</form>
</div>
</body>
<script type="text/javascript" src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=false&amp;key=<?php echo $gMapsApiKey;?>"></script>
<script type="text/javascript" src="/js/openlayers/OpenLayers.js"></script>
<script type="text/javascript" src="/js/openlayers/proj4js-combined.js"></script>
<script type="text/javascript" src="/js/openlayers/defs/EPSG900913.js"></script>
<script type="text/javascript" src="/js/ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="/js/ext/ext-all.js"></script>
<script type="text/javascript" src="/js/GeoExt/script/GeoExt.js"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
</html>
