#!/usr/bin/php
<?php

use app\conf\App;
use \app\models\Database;
use app\models\Layer;

header("Content-type: text/plain");
include_once(__DIR__ . "/../conf/App.php");
new App();

$shortopts  = "";
$shortopts .= "h:";
$shortopts .= "k:";

$options = getopt($shortopts);

if (!isset($options["h"])) {
    echo "usage:\n";
    echo "  build_indexes [options]\n";
    echo "    -h       GC2 host\n";
    echo "    -k       API key\n";
    exit();
}
$host = $options["h"];
$key = $options["k"];

$database = new Database();
$arr = $database->listAllDbs();

foreach ($arr['data'] as $db) {
    if ($db != "template1" AND $db != "template0" AND $db != "postgres" AND $db != "postgis_template" AND $db != "mapcentia") {
        Database::setDb($db);
        $layer = new Layer();
        $meta = $layer->getAll(null, null, true, false, true, true);

        /*$url = "http://{$host}/api/v1/elasticsearch/delete/{$db}*";
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        echo curl_exec($ch)."\n\n";
        curl_close($ch);*/

        if (isset($meta["data"])) {
            foreach ($meta["data"] as $l) {
                if ($l["indexed_in_es"]) {
                    $url = "http://{$host}/api/v1/elasticsearch/river/{$db}/{$l["f_table_schema"]}/{$l["f_table_name"]}?key={$key}";
                    echo $url."\n";
                    $ch = curl_init($url);
                    curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );
                    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
                    curl_setopt($ch, CURLOPT_POSTFIELDS, "key={$key}");
                    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                    echo curl_exec($ch)."\n\n";
                    curl_close($ch);
                }
            }
        }
    }
}